[package]
name = "posthog-rs"
version = "0.1.0"
authors = ["christos <christos@openquery.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
